apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-101-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yourusername/jenkins-101
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins-101
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

